# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainViewerWindow(object):
    def setupUi(self, MainViewerWindow):
        MainViewerWindow.setObjectName("MainViewerWindow")
        MainViewerWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(parent=MainViewerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoPlotLayout = QtWidgets.QHBoxLayout()
        self.videoPlotLayout.setObjectName("videoPlotLayout")
        self.videoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.videoLabel.setObjectName("videoLabel")
        self.videoPlotLayout.addWidget(self.videoLabel)
        self.plotWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.plotWidget.setObjectName("plotWidget")
        wa_native = getattr(QtCore.Qt, "WA_NativeWindow", None)
        if wa_native is None:
            wa_enum = getattr(QtCore.Qt, "WidgetAttribute", None)
            if wa_enum is not None:
                wa_native = getattr(wa_enum, "WA_NativeWindow", None)
        if wa_native is not None:
            self.plotWidget.setAttribute(wa_native, True)
        self.videoPlotLayout.addWidget(self.plotWidget)
        self.verticalLayout.addLayout(self.videoPlotLayout)
        self.metadataTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.metadataTable.setObjectName("metadataTable")
        self.metadataTable.setColumnCount(0)
        self.metadataTable.setRowCount(0)
        self.verticalLayout.addWidget(self.metadataTable)
        self.prevButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prevButton.setObjectName("prevButton")
        self.verticalLayout.addWidget(self.prevButton)
        self.nextButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nextButton.setObjectName("nextButton")
        self.verticalLayout.addWidget(self.nextButton)
        self.exportButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.importVideoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.importVideoButton.setObjectName("importVideoButton")
        self.verticalLayout.addWidget(self.importVideoButton)
        MainViewerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainViewerWindow)
        self.menubar.setObjectName("menubar")
        MainViewerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainViewerWindow)
        self.statusbar.setObjectName("statusbar")
        MainViewerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainViewerWindow)
        QtCore.QMetaObject.connectSlotsByName(MainViewerWindow)

    def retranslateUi(self, MainViewerWindow):
        _translate = QtCore.QCoreApplication.translate
        MainViewerWindow.setWindowTitle(_translate("MainViewerWindow", "Video Spectra Viewer"))
        self.prevButton.setText(_translate("MainViewerWindow", "Previous Frame"))
        self.nextButton.setText(_translate("MainViewerWindow", "Next Frame"))
        self.exportButton.setText(_translate("MainViewerWindow", "Export Metadata"))
        self.importVideoButton.setText(_translate("MainViewerWindow", "Import Video"))
